[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

#[lib]
#crate-type = ["cdylib", "rlib"]

[features]


[dependencies]
wasm-bindgen = "0.2"


[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "s"