[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"


[[bin]]
name = "duid-dev"
path = "src/tools/dev.rs"

[[bin]]
name = "duid-serve"
path = "src/tools/serve.rs"

[[bin]]
name = "duid-build"
path = "src/tools/build.rs"

[[bin]]
name = "duid-serve"
path = "src/tools/serve.rs"

[features]


[dependencies]
wasm-bindgen = "0.2"


[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "s"