[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


[tasks.build]
linux_alias = "linux_build"
windows_alias = "windows_build"
mac_alias = "mac_build"

[tasks.linux_build]
script = "echo hello"

[tasks.windows_build]
script = "echo hello"

[tasks.mac_build]
script = "echo hello"



[tasks.serve]
linux_alias = "linux_serve"
windows_alias = "windows_serve"
mac_alias = "mac_serve"

[tasks.linux_serve]
script = "echo hello"

[tasks.windows_serve]
script = "echo hello"

[tasks.mac_serve]
script = "echo hello"



[tasks.deploy]
linux_alias = "linux_deploy"
windows_alias = "windows_deploy"
mac_alias = "mac_deploy"

[tasks.linux_deploy]
script = "echo hello"

[tasks.windows_deploy]
script = "echo hello"

[tasks.mac_deploy]
script = "echo hello"