# If you are in a workspace then please uncomment two lines bellow
#[env]
#CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


[tasks.dev]
command = "wasm-pack build --target web --release"
#linux_alias = "linux_dev"
#windows_alias = "windows_dev"
#mac_alias = "mac_dev"

#[tasks.linux_dev]
#script = "echo hello"

#[tasks.windows_dev]
#command = "wasm-pack build --target web --release"

#[tasks.mac_dev]
#script = "echo hello"
