# If you are in a workspace then please uncomment two lines bellow
#[env]
#CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


[tasks.dev]
command = "wasm-pack"
args = ["build", "--target", "web", "--release"]
